posts:
  label: Posts
  view:
    showSearch: true
    list:
      columns:
        title:
          label: rainlab.blog::lang.post.title
          sortable: true
          searchable: true
        value:
          type: partial
          path: custom_value
        published_at:
          label: rainlab.blog::lang.post.published
          sortable: true
          type: date
        created_at:
          label: rainlab.blog::lang.post.created
          type: date
          sortable: true
    form:
      title: 
        type: text
    toolbarButtons: add|remove
  manage:
    showSearch: true
    list:
      columns:
        title:
          label: rainlab.blog::lang.post.title
          searchable: true
          sortable: true
        published_at:
          label: rainlab.blog::lang.post.published
          type: date
          sortable: true
        created_at:
          label: rainlab.blog::lang.post.created
          type: date
          sortable: true

